pipeline{
    agent {
        label 'AGENT-1'
    }
    environment{
        project="expense"
        component="backend"
    }
    options { 
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
        }
    parameters {

        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Pick something')

    }
    stages{
        stage('init'){

            steps{
                script{
                    withAWS(region: 'us-east-1', credentials: 'aws-creds'){
                    sh """
                       cd 00-vpc
                       terraform init -reconfigure
                       terraform plan
                    """
                    }
                  
                }
            }
        }
        stage('apply'){
            steps{
                script{
                    withAWS(region: 'us-east-1', credentials: 'aws-creds'){
                    sh """
                       cd 00-vpc
                       terraform apply -auto-approve
                    """
                    }

                }
            }
        }
        stage('trigger sg'){
            when { 
                expression { params.ACTION == 'apply'}
            }
            steps {
                     build job: '10-sg', parameters: [string(name: 'ACTION', value: 'apply')], wait: false
                    }

                 
        }


    }
    post{
        always{
            echo "say hello always"
            deleteDir()
        }
        success{
            echo "say hello in success"
        }
        failure{
            echo "say hello in failure"
        }
        unsuccessful{
            echo "say hello in unsuccessful"
        }
    }
}