pipeline{
        agent{
        label 'AGENT-1'
    }
    environment{
        project="expense"
        component="backend"
    }
    options { 
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
        }
    parameters {

        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Pick something')

    }
    stages{
        stage('init'){

            steps{
                script{
                    withAWS(region: 'us-east-1', credentials: 'aws-cred'){
                    sh """
                       cd 10-sg
                       terraform init -reconfigure
                       terraform plan
                    """
                    }
                  
                }
            }
        }
        stage('apply'){
            steps{
                script{
                    withAWS(region: 'us-east-1', credentials: 'aws-cred'){
                    sh """
                       cd 10-sg
                       terraform apply -auto-approve
                    """
                    }
                  

                }
            }
        }
        stage('Parallel Stages') {
            when { 
                expression { params.ACTION == 'apply'}
            }
            parallel {
                stage('20-bastion') {    
                    steps {
                        build job: '20-bastion', parameters: [string(name: 'ACTION', value: 'apply')], wait: false
                    }
                }
                stage('30-rds') {
                    steps {
                        build job: '30-rds', parameters: [string(name: 'ACTION', value: 'apply')], wait: false
                    }
                }
                stage('40-eks') {
                    steps {
                        build job: '40-eks', parameters: [string(name: 'ACTION', value: 'apply')], wait: false
                    }
                }
                stage('50-ecr') {
                    steps {
                        build job: '50-ecr', parameters: [string(name: 'ACTION', value: 'apply')], wait: false
                    }
                }
            }
        }
    }

    post{
        always{
            echo "say hello always"
            deleteDir()
        }
        success{
            echo "say hello in success"
        }
        failure{
            echo "say hello in failure"
        }
    }
}